### PR TITLE
Fix Travis CI 

### PR DESCRIPTION
**Pull request by RJ722**
Closes: #80

### CODE REVIEW

**Comment by jendrikseipp** [comment]
I think we should be using the Trusty images. I tried to apply a different fix from https://github.com/travis-ci/travis-ci/issues/6865 and https://github.com/travis-ci/travis-cookbooks/pull/861, but so far no luck... It would be great if you could investigate some more. If you don't find a way to use pypy on Trusty, we can use the Precise images.

**Comment by RJ722** [comment]
Hi @jendrikseipp 
I just realised I have named the PR and the commit wrongly. Changing them.

Do you think it is a good idea to test these on the master branch?

**Comment by RJ722** [comment]
Strange, if we change `pypy2-5.8.0` to `pypy2.7-5.8.0`, it works 😅 

Looks like a upstream bug?

**Comment by RJ722** [comment]
Although https://github.com/travis-ci/travis-ci/issues/6865#issuecomment-317819856 mentions that it should now work for every infrastructure, it doesn't works for commits prior to this one. I tried restarting the build for an other PR (#79), but still no effect.  :-(

**Comment by jendrikseipp** [comment]
You're right, I shouldn't have tried to fix this in master. Thanks for looking into this!

**Pull request merged**
