### PR TITLE
Add whitelist for the pint package

### PR DESCRIPTION
**Pull request by bje-**
Self-evident.

### CODE REVIEW

**Review by RJ722 — COMMENTED** [review]
Thanks for the pull request @bje-! 

I think that we need to think some more about shipping whitelists for non-stdlib modules with Vulture. I can think of the following options:

1. We wrap the entire script in a try/except block which will only run if the module can be imported successfully.
2. Use the proxy `Whitelist` module from `whitelists/whitelist_utils.py`.

@jendrikseipp any thoughts?

---

I also had an initial worry that using common names (like in this case, `default_format`) might be used too often altogether and that Vulture might miss them as false negatives, but now that I think of it, since we only import the whitelists only if the corresponding module is imported in user's program, I don't think this will be a problem.

**Comment by RJ722** [comment]
Oh I just found out https://github.com/jendrikseipp/vulture/issues/208#issuecomment-637369208 from @jendrikseipp:

> Actually, i think it's good to use "real" source code in whitelists. That way, we can test that the names really exist and are spelled correctly. The whitelist files that are bundled with Vulture are only used when the corresponding module is imported, and even then the content is only parsed for names, not actually run, so no new dependency is needed. We only need to add flask or its extensions to the tox.ini testenv section and this allows us to actually run the whitelist file during testing.

I too think this is a good idea, and I think, it answers all the questions above.

@bje- can you add `pint` to the tox.ini testenv section? That should fix the CI and we should be good to go.

**Comment by bje-** [comment]
Like so?

**Review by jendrikseipp — CHANGES_REQUESTED** [review]
Looks good to me! Can you add a changelog entry, please?

**Comment by jendrikseipp** [comment]
Thanks!

**Comment by bje-** [comment]
And thank you!

**Pull request merged**
