### PR TITLE
Proposal: Enable DeepSource for detecting issues

### PR DESCRIPTION
**Pull request by RJ722**
## Description

Hey @jendrikseipp,

I ran [DeepSource][ds] on Vulture, and found several interesting issues - https://deepsource.io/gh/RJ722/vulture/issues/ - some of which I think we should fix. (Let's also use this PR to triage these issues)

Also, I think that it would be helpful to have DeepSource enabled here on the main repos, so that we get to see analysis results for all new PRs, and catch issues early on.

Also, a disclaimer: I am currently a part of the DeepSource team, working on their analyzers.

[ds]: https://deepsource.io/

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation in the README file.
- [ ] I have updated the documentation accordingly.
- [ ] I have added an entry in CHANGELOG.md.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jendrikseipp** [comment]
Thanks for looking into this! The DeepSource report is interesting, but only contains a few issues that I'd actually like to fix:

https://deepsource.io/gh/RJ722/vulture/issue/PYL-E0101/occurrences
https://deepsource.io/gh/RJ722/vulture/issue/PYL-W0613/occurrences
https://deepsource.io/gh/RJ722/vulture/issue/PYL-W0201/occurrences

I think these should be tackled in a separate PR.

Regarding adding DeepSource to Vulture's CI, I doubt that it's worth the trouble, since we would need to maintain a long list of false positives. But feel free to compile this list and let's see how complicated it is.

**Comment by RJ722** [comment]
Thanks for traiging the issues! Apart from the ones you mentioned, I think that we should also fix the following:

- https://deepsource.io/gh/RJ722/vulture/issue/BAN-B101/occurrences
- https://deepsource.io/gh/RJ722/vulture/issue/PYL-R1705/occurrences

What do you think?

Also, I'd open individual GitHub issues for each one of these, which could be then publicised as "Good First Issues".

> But feel free to compile this list and let's see how complicated it is.

Thanks! I've added the `# skipcq` comments in this PR itself.

Other than this, there isn't much maintainence overhead either - I added the following issues to be ignored repository wide (single button click) -- found them too stringent for my taste:

* One line docstring should fit on one line with quotes.
* Missing docstring in public function
* Audit required: Detected subprocess call
* Import of `subprocess` module detected.

Screen Shot 2020-04-10 at 11 05 58 PM

**Comment by jendrikseipp** [comment]
I think the assert statement is fine. It will catch programming errors when running things unoptimized locally. The "unnecessary else" case is a question of style preference. Personally, I often like the symmetry of the if-else structure.

> Also, I'd open individual GitHub issues for each one of these, which could be then publicised as "Good First Issues".

I appreciate the idea, but I think fixing these directly would require much less work.

> Thanks! I've added the # skipcq comments in this PR itself.

I think these make the code harder to read. I think the DeepSource results contain too many false positives for the system to be run in CI. In other words, it's interesting to see these results, but I don't think it's a good benefit/work ratio to add them to our permanent test suite. We may want to revisit this once DeepSource supports more interesting tests and produces fewer false positives.

**Comment by RJ722** [comment]
> > Also, I'd open individual GitHub issues for each one of these, which could be then publicised as "Good First Issues".

> I appreciate the idea, but I think fixing these directly would require much less work.

Okay, let me fix them in a separate PR.

> I think these make the code harder to read. I think the DeepSource results contain too many false positives for the system to be run in CI. In other words, it's interesting to see these results, but I don't think it's a good benefit/work ratio to add them to our permanent test suite. We may want to revisit this once DeepSource supports more interesting tests and produces fewer false positives.

Thanks for the feedback! :)

**Pull request closed without merging**
