### PR TITLE
Put test case for visit_FunctionDef

### PR DESCRIPTION
**Pull request by jack17529**
Using async/await to test the visit_FunctionDef

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation in the README file.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jack17529** [comment]
I think I don't need await in assert statements.

**Comment by jack17529** [comment]
Should I write all aspects of property and function like you have covered, I could not find that on internet.

**Comment by jendrikseipp** [comment]
It should be enough to test for used and unused async functions. 

Please tell me when you're done with this pull request and all tests pass.

**Comment by jendrikseipp** [comment]
Closing since the PR seems to be abandoned. Feel free to reopen.

**Pull request closed without merging**
